export const GET_EMPLOYEE_DETAIL = "GET_EMPLOYEE_DETAIL";
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"